credentials:
  usernames:
    admin:
      email: admin@example.com
      name: Admin User
      password: $2b$12$examplehashedpassword  # Use stauth.Hasher to generate
cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
preauthorized:
  emails:
    - admin@example.com